sudo: false
language: python
python:
  - 3.5
env:
  - INFOSET_CONFIGDIR=$HOME/infoset_unittests/config
before_install: $HOME/infoset/test/create_test_config.py
install: python3 $HOME/setup.py
script: $HOME/infoset/test/_do_all_tests.py
