sudo: false
language: python
python:
  - 3.5
env:
  - INFOSET_CONFIGDIR=~/.infoset_unittests/config
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
before_install: infoset/test/create_test_config.py
install: python3 setup.py
script: tox
cache:
  directories:
    - .tox
    - $HOME/.cache/pip
