infoset:
  build: .
  ports:
    - "6000:6000"
  links:
    - redis
  hostname: localhost
  environment:
    PYTHONPATH: /infoset-ng
celery:
  build: .
  command: celery worker -A infoset.api.post.celery --loglevel=debug
  links:
    - redis
  volumes:
    - ./:/infoset-ng
redis:
  hostname: localhost
  image: redis:latest
  ports:
    - "6379:6379"
