infoset:
  build: .
  ports:
    - "6000:6000"
  links:
    - mysql
  hostname: localhost
  environment:
    PYTHONPATH: /infoset-ng
mysql:
  hostname: localhost
  build: ./docker/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_USER: root
    MYSQL_DATABASE: infoset
    MYSQL_ROOT_PASSWORD: password
