main:
  db_file: infoset-db.db
  bind_port: 6000
  db_hostname: localhost
  db_name: infoset
  db_password: password
  db_username: root
  ingest_cache_directory: cache
  ingest_pool_size: 20
  interval: 60
  listen_address: 0.0.0.0
  log_directory: log
  log_level: debug
  memcached_hostname: localhost
  memcached_port: 11211
  sqlalchemy_max_overflow: 10
  sqlalchemy_pool_size: 10
  username: infoset